title: ts-data-generator
site_title: ts-data-generator
description: "A professional-grade Python library and CLI for generating realistic, deterministic, and anomaly-injected time series datasets."
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/logo.svg"
theme: jekyll-theme-cayman # Fallback
remote_theme: just-the-docs/just-the-docs

# Site Settings
baseurl: "/ts-data-generator" # Standard for project pages
url: "https://manojmanivannan.github.io"

# Metadata
repository: manojmanivannan/ts-data-generator
author: Manoj Manivannan

# Just the Docs Settings
search_enabled: true
aux_links:
  "GitHub Repository": "https://github.com/manojmanivannan/ts-data-generator"

# Markdown Engine
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

# Navigation
nav_sort: ord
